//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRG4_MG2P2_0320190026_B2.UserControl
{


    public partial class NavbarWhite
    {
    }
}
